logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  application:
    name: aib-data
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
  datasource:
    platform: h2
    initialization-mode: always
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
eureka:
  client:
    enabled: false

server:
  port: 8081

images:
  pathToFolder: C:\Users\Dmitry\Desktop\poehali\aib-backend\aib-data\src\main\resources\images