logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  application:
    name: aib-data
  datasource:
    platform: h2
  h2:
    console:
      enabled: true
eureka:
  client:
    enabled: false

server:
  port: 8081

images:
  pathToFolder: C:\dev\aib-backend\aib-data\src\main\resources\images