INSERT INTO board (id, title, genre)
VALUES
('a', 'Anime', 'JAPAN'),
('mng', 'Manga', 'JAPAN'),
('m', 'Mecha', 'JAPAN'),
('jp', 'Otaku Culture', 'JAPAN'),
('v', 'Video Games', 'GAMES'),
('vp', 'Pokemon', 'GAMES'),
('vr', 'Retro Games', 'GAMES'),
('mmo', 'MMO Games', 'GAMES'),
('g', 'Technology', 'INTERESTS'),
('sci', 'Science', 'INTERESTS'),
('toy', 'Toys', 'INTERESTS'),
('int', 'International', 'INTERESTS'),
('an', 'Animals', 'INTERESTS'),
('his', 'History', 'INTERESTS'),
('p', 'Photography', 'CREATIVE'),
('ck', 'Food & Cooking', 'CREATIVE'),
('po', 'Papercraft & Origami', 'CREATIVE'),
('ic', 'Artwork', 'CREATIVE'),
('walp', 'Wallpapers', 'CREATIVE'),
('mu', 'Music', 'CREATIVE'),
('lit', 'Literature', 'CREATIVE'),
('gd', 'Graphic Design', 'CREATIVE'),
('fa', 'Fashion', 'CREATIVE');
