logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  application:
    name: aib-data

eureka:
  client:
    enabled: false

images:
  pathToFolder: C:\dev\aib-backend\aib-data\src\main\resources\images